backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

site_url: "https://almuhalil.netlify.app"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        name: "home"
        label: "Home Page"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
